########################################
# FICL (Forth Inspired Command Language)
########################################

option(BUILD_WITH_FICL "FICL Enabled" ${BUILD_WITH_ALL})
message("BUILD_WITH_FICL: ${BUILD_WITH_FICL}")

if(BUILD_WITH_FICL)

    set(FICL_DIR ${THIRDPARTY_DIR}/ficl)

    # Generate softcore.c from softwords if it doesn’t exist
    if(NOT EXISTS ${FICL_DIR}/softcore.c)
        message(STATUS "Generating softcore.c from softwords…")
        # softcore.c is generated by softcore.py from .fr files For simplicity,
        # include the softwords source at compile time
    endif()

    # FICL source files
    set(FICL_SRC
        ${FICL_DIR}/dict.c
        ${FICL_DIR}/ficl.c
        ${FICL_DIR}/fileaccess.c
        ${FICL_DIR}/float.c
        ${FICL_DIR}/dpmath.c
        ${FICL_DIR}/prefix.c
        ${FICL_DIR}/search.c
        ${FICL_DIR}/stack.c
        ${FICL_DIR}/sysdep.c
        ${FICL_DIR}/tools.c
        ${FICL_DIR}/vm.c
        ${FICL_DIR}/words.c
    )

    # Add softcore.c if it exists
    if(EXISTS ${FICL_DIR}/softcore.c)
        list(APPEND FICL_SRC ${FICL_DIR}/softcore.c)
    endif()

    # Create the FICL library
    add_library(ficl STATIC ${FICL_SRC})

    # Enable floats, locals, & OOP
    target_compile_definitions(ficl PRIVATE
        FICL_WANT_FLOAT=1
        FICL_WANT_LOCALS=1
        FICL_WANT_OOP=1
    )

    target_include_directories(ficl
        PRIVATE
            ${FICL_DIR}
            ${CMAKE_SOURCE_DIR}/include
            ${CMAKE_SOURCE_DIR}/src
    )

    # Create the TIC-80 FICL binding
    add_library(ficl_script ${TIC_RUNTIME}
        ${CMAKE_SOURCE_DIR}/src/api/ficl.c
        ${CMAKE_SOURCE_DIR}/src/api/parse_note.c
    )

    if(NOT BUILD_STATIC)
        set_target_properties(ficl_script PROPERTIES PREFIX "")
    else()
        target_compile_definitions(ficl_script INTERFACE TIC_BUILD_WITH_FICL=1)
    endif()

    target_link_libraries(ficl_script PRIVATE runtime ficl)

    target_include_directories(ficl_script
        PRIVATE
            ${FICL_DIR}
            ${CMAKE_SOURCE_DIR}/include
            ${CMAKE_SOURCE_DIR}/src
    )

endif()
